import { historyArtifact } from './history-artifact.mjs';
import { packageSnapshot } from './package.mjs';
import { interactiveReview } from './review.mjs';
import { promises as fs } from 'node:fs';
import { join, resolve } from 'node:path';
import { load, status, versions } from './engine.mjs';
import { readJSON, atomic } from './shared/io.mjs';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export async function report(file) {
  const c=await load(file),s=await status(file),r=s.latest;
  const history=await versions(file);
  const currentPackage=await packageSnapshot(c);
  const assessment=r?.packageAssessment??await readJSON(join(c.state,'package-assessment.json'),null);
  const packageStale=assessment&&assessment.packageHash!==currentPackage.hash;
  const packageSection=`<section><div class="eyebrow">DEFAULT PACKAGE ASSESSMENT</div><h2>The whole selected package.</h2><p>${assessment?`${assessment.summary.total} components inventoried · ${assessment.summary.tested} execution-tested · ${assessment.summary.untested} untested · ${assessment.summary.unsupported} unsupported · ${assessment.summary.blocked} blocked references`:'This historical run assessed only the main skill file. Run a fresh assessment to include supporting components.'}</p>${packageStale?'<p class="fail">Package changed since this evidence was captured. Retest before relying on this report.</p>':''}<p class="muted">${esc(assessment?.coverage??'Package coverage has not been recorded.')}</p><p>${esc(assessment?.note??'Supporting files have no recorded QA evidence.')}</p><div class="scroll"><table><thead><tr><th>Component</th><th>Type</th><th>Status</th><th>Evidence</th></tr></thead><tbody>${(assessment?.components??[]).map(f=>`<tr><td>${esc(f.path)}</td><td>${esc(f.kind)}</td><td class="${f.status==='passed'?'pass':f.status==='failed'?'fail':'muted'}">${esc(f.status)}</td><td>${esc(f.reason)}</td></tr>`).join('')}</tbody></table></div>${(assessment?.issues??[]).map(i=>`<p class="fail">${esc(i.path)}: ${esc(i.reason)}</p>`).join('')}<details><summary>Configured component-test evidence</summary><pre>${esc(JSON.stringify(assessment?.tests??[],null,2))}</pre></details><details><summary>Excluded paths</summary><pre>${esc(JSON.stringify(assessment?.exclusions??[],null,2))}</pre></details></section>`;
  const saved=r?await readJSON(join(c.state,'runs',r.id+'.json')):null;
  const writingCases=(saved?.request?.cases??[]).filter(x=>typeof x.input?.text==='string');
  const outputs=writingCases.length?`<section><div class="eyebrow">THE WORK · BEFORE AND AFTER</div><h2>Read the actual output.</h2>${writingCases.map(x=>{const out=saved.response.outputs.find(o=>o.id===x.id)?.output;return `<h3>${esc(x.id)}</h3><div class="versions"><article><h4>Source text</h4><pre>${esc(x.input.text)}</pre></article><article><h4>Skill output</h4><pre>${esc(typeof out?.text==='string'?out.text:JSON.stringify(out,null,2))}</pre></article></div>`;}).join('')}<p class="muted">These are saved inputs and outputs from this run. Review meaning and tone alongside the automated checks.</p></section>`:'';
  const names=await fs.readdir(join(c.state,'proposals')).catch(e=>{if(e.code==='ENOENT')return [];throw e;});
  const proposals=await Promise.all(names.filter(n=>n.endsWith('.json')).map(n=>readJSON(join(c.state,'proposals',n))));
  const review=await interactiveReview(file,c,history);
  const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Skill Loop · Jordaaan</title><style>
  :root{color-scheme:dark;--bg:#0a0908;--surface:#141210;--surface-2:#1c1815;--line:#2b2620;--text:#f5efe6;--text-dim:#8c8478;--gold:#d9a441;--gold-dim:#a67d33;--mono:'IBM Plex Mono','SF Mono',Consolas,monospace;--sans:'IBM Plex Sans',-apple-system,Helvetica,Arial,sans-serif}*{box-sizing:border-box}body{background:var(--bg);color:var(--text);font:16px/1.55 var(--sans);margin:0}main{max-width:1050px;margin:auto;padding:35px 22px}h1{font:600 clamp(32px,5vw,52px)/1.08 var(--mono);letter-spacing:-.01em;margin:20px 0;max-width:20ch}h1 span{color:var(--gold)}h2{font:600 clamp(22px,3vw,30px)/1.25 var(--mono)}.eyebrow{color:var(--gold);letter-spacing:.08em;font:12px var(--mono)} .cards,.versions{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.card,section{background:var(--surface);border:1px solid var(--line);border-radius:8px;padding:20px;margin:16px 0}.number{font-size:32px;display:block}.muted{color:#b7ada0}.pass{color:#88d3a3}.fail{color:#ffae8e}table{width:100%;border-collapse:collapse}td,th{text-align:left;border-bottom:1px solid var(--line);padding:12px}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:var(--surface-2);padding:18px}.versions{grid-template-columns:1fr 1fr}.scroll{overflow:auto}summary{cursor:pointer}footer{margin-top:32px;color:#b7ada0}@media(max-width:650px){.cards,.versions{grid-template-columns:1fr}.card{margin:0}}.report-brand{display:flex;justify-content:space-between;gap:16px;flex-wrap:wrap;border-bottom:1px solid var(--line);padding:0 0 22px;margin-bottom:40px;font:12px var(--mono)}.report-brand>span:first-child{font-size:16px}.report-brand b{color:var(--gold)}</style>
  <main><header class="report-brand"><span>skill<b>-loop</b></span><span>ORGANIZED AI · WITH JORDAAAN</span></header><div class="eyebrow">// QA REVIEW · SAVED EVIDENCE</div><h1>Test your skills.<br><span>Improve with evidence.</span></h1><p class="muted">Local test evidence · ${esc(s.runner)} · ${esc(r?.createdAt??'No completed run')}</p>
  <div class="cards"><div class="card">Latest score<strong class="number">${r?`${r.passed} / ${r.total}`:'—'}</strong></div><div class="card">Baseline<strong class="number">${s.baseline?`${s.baseline.passed} / ${s.baseline.total}`:'Not saved'}</strong></div><div class="card">Effectiveness drift<strong class="number">${esc(!r?'Not tested':r.comparison.status==='regression'?'Detected':r.id===s.baseline?.id?'Baseline saved':r.comparison.status==='no-baseline'?'Needs baseline':r.comparison.status==='incomparable'?'Not comparable':'Not detected')}</strong></div></div>
  <section><div class="eyebrow">MORE REPEATABLE OVER TIME</div><h2>Reduce variation. Detect drift.</h2><p>Skill Loop aims to make skills more predictable by moving repeatable work into deterministic rules, scripts, and validated output formats wherever practical. The assistant can propose improvements; fixed checks evaluate the results.</p><p>Compare revisions against the same QA rules, preserve a baseline, and retest before adopting a change. Repeated live runs are needed to measure output variation. A higher score on one run does not prove reduced variance or prevent future drift.</p><p class="muted">This report shows the evidence collected for this run. Deterministic or replay checks verify repeatable behavior within their scope; they do not establish reliability for every LLM response.</p></section>
  ${packageSection}
  ${outputs}
  ${review}
  <section><h2>Connect → Baseline → Detect drift → Test → Review</h2><p>Effectiveness drift means a previously passing check now fails under comparable test conditions. A changed suite or runner configuration needs a new baseline; it is not proof of effectiveness drift. Only a reviewed approval changes your skill. This report is a snapshot; regenerate it after a run or decision. A higher fixture score does not establish general reliability.</p></section>
  <section><h2>QA source and coverage</h2><p><strong>${esc(r?.qaSource?.title??'QA source not specified')}</strong> · ${esc(r?.qaSource?.reference??'Add a source of truth to the test suite')} · ${esc(r?.qaSource?.version??'Unversioned')}</p><p>${esc(r?.coverage??'Only the supplied cases are evaluated.')}</p><p class="muted">The engine checks output against these rules. It does not independently certify that the rules are correct or complete.</p></section><section><h2>Test evidence</h2><div class="scroll"><table><thead><tr><th>Case</th><th>Check</th><th>Result</th><th>Actual</th><th>Expected</th></tr></thead><tbody>${(r?.checks??[]).map(x=>`<tr><td>${esc(x.caseId)}</td><td>${esc(x.path)} ${esc(x.op)}</td><td class="${x.passed?'pass':'fail'}">${x.passed?'Pass':'Fail'}</td><td>${esc(JSON.stringify(x.actual))}</td><td>${esc(JSON.stringify(x.expected))}</td></tr>`).join('')}</tbody></table></div></section>
  <section><h2>Saved versions</h2><p>The active version changes only through approval or an explicit version choice. A preference override can select an older version; its QA history remains visible.</p><div class="scroll"><table><tr><th>Version</th><th>Selection</th><th>QA score</th><th>Evidence</th></tr>${history.versions.map(v=>`<tr><td>${esc(v.version.slice(0,12))}</td><td>${v.active?'Active':'Saved'}</td><td>${v.passed}/${v.total}</td><td>${esc(v.qa)}</td></tr>`).join('')}</table></div></section><h2>Changes for review</h2>${proposals.length?proposals.map(p=>`<section><h3>${esc(p.status)} · ${p.versionChoice?'User-selected version':p.eligible?'Passed improvement gate':'Did not pass improvement gate'}</h3><p>${esc(p.evidence)}</p><details><summary>Compare original and candidate</summary><div class="versions"><div><h4>Original</h4><pre>${esc(p.before)}</pre></div><div><h4>Candidate</h4><pre>${esc(p.candidate)}</pre></div></div></details><p class="muted">Proposal ${esc(p.id)}</p></section>`).join(''):'<p>No proposals yet.</p>'}
  ${historyArtifact({saved,history,proposals,assessment})}<footer>Brain Gainz with Jordaaan · Skill Loop 0.1 · QA evidence snapshot · sharing follows your assistant’s settings.</footer></main></html>`;
  const path=join(c.state,'report.html');await atomic(path,html);return {report:path,artifact:{title:"Skill Loop QA Review · Jordaaan",mimeType:"text/html",path,preferredPresentation:"interactive-artifact",selfContained:true}};
}
