import { promises as fs } from 'node:fs';
import { join, resolve } from 'node:path';
import { load, status, versions } from './engine.mjs';
import { readJSON, atomic } from './shared/io.mjs';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export async function report(file) {
  const c=await load(file),s=await status(file),r=s.latest;
  const history=await versions(file);
  const names=await fs.readdir(join(c.state,'proposals')).catch(e=>{if(e.code==='ENOENT')return [];throw e;});
  const proposals=await Promise.all(names.filter(n=>n.endsWith('.json')).map(n=>readJSON(join(c.state,'proposals',n))));
  const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Skill Loop · Jordaaan</title><style>
  :root{color-scheme:dark}*{box-sizing:border-box}body{background:#11110f;color:#ecebe2;font:16px/1.6 system-ui;margin:0}main{max-width:1050px;margin:auto;padding:35px 22px}h1{font-size:clamp(32px,6vw,60px);margin:15px 0}h2{font-size:23px}.eyebrow{color:#d9a441;letter-spacing:.12em;font-size:12px} .cards,.versions{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.card,section{border:1px solid #393831;border-radius:12px;padding:20px;margin:16px 0}.number{font-size:32px;display:block}.muted{color:#afada2}.pass{color:#88d3a3}.fail{color:#ffae8e}table{width:100%;border-collapse:collapse}td,th{text-align:left;border-bottom:1px solid #393831;padding:12px}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#1b1b18;padding:18px}.versions{grid-template-columns:1fr 1fr}.scroll{overflow:auto}summary{cursor:pointer}footer{margin-top:32px;color:#afada2}@media(max-width:650px){.cards,.versions{grid-template-columns:1fr}.card{margin:0}}</style>
  <main><div class="eyebrow">JORDAAAN / ORGANIZED AI</div><h1>Spot drift. Test the fix.</h1><p class="muted">Local test evidence · ${esc(s.runner)} · ${esc(r?.createdAt??'No completed run')}</p>
  <div class="cards"><div class="card">Latest score<strong class="number">${r?`${r.passed} / ${r.total}`:'—'}</strong></div><div class="card">Baseline<strong class="number">${s.baseline?`${s.baseline.passed} / ${s.baseline.total}`:'Not saved'}</strong></div><div class="card">Effectiveness drift<strong class="number">${esc(!r?'Not tested':r.comparison.status==='regression'?'Detected':r.comparison.status==='no-baseline'?'Needs baseline':r.comparison.status==='incomparable'?'Not comparable':'Not detected')}</strong></div></div>
  <section><h2>Connect → Baseline → Detect drift → Test → Review</h2><p>Effectiveness drift means a previously passing check now fails under comparable test conditions. A changed suite or runner configuration needs a new baseline; it is not proof of effectiveness drift. Only a reviewed approval changes your skill. This report is a snapshot; regenerate it after a run or decision. A higher fixture score does not establish general reliability.</p></section>
  <section><h2>QA source and coverage</h2><p><strong>${esc(r?.qaSource?.title??'QA source not specified')}</strong> · ${esc(r?.qaSource?.reference??'Add a source of truth to the test suite')} · ${esc(r?.qaSource?.version??'Unversioned')}</p><p>${esc(r?.coverage??'Only the supplied cases are evaluated.')}</p><p class="muted">The engine checks output against these rules. It does not independently certify that the rules are correct or complete.</p></section><section><h2>Test evidence</h2><div class="scroll"><table><thead><tr><th>Case</th><th>Check</th><th>Result</th><th>Actual</th><th>Expected</th></tr></thead><tbody>${(r?.checks??[]).map(x=>`<tr><td>${esc(x.caseId)}</td><td>${esc(x.path)} ${esc(x.op)}</td><td class="${x.passed?'pass':'fail'}">${x.passed?'Pass':'Fail'}</td><td>${esc(JSON.stringify(x.actual))}</td><td>${esc(JSON.stringify(x.expected))}</td></tr>`).join('')}</tbody></table></div></section>
  <section><h2>Saved versions</h2><p>The active version changes only through approval or an explicit version choice. A preference override can select an older version; its QA history remains visible.</p><div class="scroll"><table><tr><th>Version</th><th>Selection</th><th>QA score</th><th>Evidence</th></tr>${history.versions.map(v=>`<tr><td>${esc(v.version.slice(0,12))}</td><td>${v.active?'Active':'Saved'}</td><td>${v.passed}/${v.total}</td><td>${esc(v.qa)}</td></tr>`).join('')}</table></div></section><h2>Changes for review</h2>${proposals.length?proposals.map(p=>`<section><h3>${esc(p.status)} · ${p.versionChoice?'User-selected version':p.eligible?'Passed improvement gate':'Did not pass improvement gate'}</h3><p>${esc(p.evidence)}</p><details><summary>Compare original and candidate</summary><div class="versions"><div><h4>Original</h4><pre>${esc(p.before)}</pre></div><div><h4>Candidate</h4><pre>${esc(p.candidate)}</pre></div></div></details><p class="muted">Proposal ${esc(p.id)}</p></section>`).join(''):'<p>No proposals yet.</p>'}
  <footer>Brain Gainz with Jordaaan · Skill Loop 0.1 · Local evidence stays on this computer.</footer></main></html>`;
  const path=join(c.state,'report.html');await atomic(path,html);return {report:path};
}
