import test from 'node:test';import assert from 'node:assert/strict';
import {storagePlan} from '../scripts/cloudflare-state.mjs';
import {saveBackup,readBackup} from '../scripts/cloudflare-backup.mjs';
import {createHash} from 'node:crypto';
const hash=x=>createHash('sha256').update(x).digest('hex');
function fixture(){const files=['package/SKILL.md','suite.json','package/assets/test.bin'].map(path=>{const b=Buffer.from(path.endsWith('.bin')?[0,255,2]:[123,125]);return {path,data:b.toString('base64'),bytes:b.length,sha256:hash(b),mode:384}});const p=storagePlan({format:'skill-loop-cloudflare-state',version:1,entry:'SKILL.md',files,coverage:'Fixture',excluded:[]},{backend:'r2',skillId:'backup-test'});return {manifest:p.manifest,chunks:p.writes.map((x,i)=>({ordinal:i,value:x.value,sha256:p.manifest.chunks[i].sha256}))};}
function db(corrupt=false){const chunks=new Map(),manifests=new Map();return {manifests,query:async(sql,p=[])=>{if(sql.startsWith('CREATE'))return [];if(sql.startsWith('INSERT')&&sql.includes('checkpoint_chunks')){const k=p[0]+':'+p[1];if(!chunks.has(k))chunks.set(k,{ordinal:p[1],sha256:p[2],value:corrupt?p[3]+'x':p[3]});return [];}if(sql.startsWith('INSERT')){if(!manifests.has(p[0]))manifests.set(p[0],p[3]);return [];}if(sql.startsWith('SELECT manifest'))return manifests.has(p[0])?[{manifest:manifests.get(p[0])}]:[];if(p.length===2)return chunks.has(p[0]+':'+p[1])?[chunks.get(p[0]+':'+p[1])]:[];return [...chunks].filter(([k])=>k.startsWith(p[0]+':')).map(([,v])=>v);}};}
test('backup saves and fresh-reads all package bytes without changing existing content',async()=>{const p=fixture(),d=db();assert.deepEqual(await saveBackup(p,d.query),p);assert.deepEqual(await saveBackup(p,d.query),p);const key='v2:'+p.manifest.skillId+':'+p.manifest.id;assert.deepEqual(await readBackup(key,d.query),p);await assert.rejects(()=>readBackup(key.replace('backup-test','other'),d.query),/not found/);});
test('corrupted chunk fails before manifest commit',async()=>{const d=db(true);await assert.rejects(()=>saveBackup(fixture(),d.query),/mismatch/);assert.equal(d.manifests.size,0);});
