import test from 'node:test';
import assert from 'node:assert/strict';
import {promises as fs} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {createSetup,setupStatus,checkSetup,connectSetup,probeStorage} from '../scripts/setup.mjs';
async function fixture(t){const dir=await fs.mkdtemp(join(tmpdir(),'skill-setup-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const root=join(dir,'skills','user-skill');await fs.mkdir(root,{recursive:true});await fs.writeFile(join(root,'SKILL.md'),'Preserve numbers when summarizing text.');return {dir,root};}
function database(corrupt=false){const rows=new Map();return {rows,query:async(sql,p=[])=>{if(sql.startsWith('INSERT'))rows.set(p[0],{value:p[1],sha256:p[2]});if(sql.startsWith('SELECT')){const row=rows.get(p[0]);return row?[{...row,...(corrupt?{value:'changed'}:{})}]:[];}if(sql.startsWith('DELETE'))rows.delete(p[0]);return [];}};}
test('setup persists preferences and produces fresh reports on repeated use without examples',async t=>{const {dir,root}=await fixture(t);const s=await createSetup(join(dir,'profile'),'codex',[root]);assert.equal(s.readyForLocalOverview,false);const a=await checkSetup(s.profile),b=await checkSetup(s.profile);assert.equal(b.readyForLocalOverview,true);assert.equal(b.cloudReady,false);assert.notEqual(a.steps[1].detail.report,b.steps[1].detail.report);assert.equal(await fs.readFile(join(root,'SKILL.md'),'utf8'),'Preserve numbers when summarizing text.');assert.equal((await setupStatus(s.profile)).assistant,'codex');await assert.rejects(createSetup(join(dir,'profile'),'codex',[root]),/never overwritten/);});
test('no skills stays incomplete and cannot appear cloud-ready',async t=>{const {dir}=await fixture(t);const s=await createSetup(join(dir,'profile'),'claude-desktop',[join(dir,'absent')]);const r=await checkSetup(s.profile);assert.equal(r.readyForLocalOverview,false);assert.equal(r.cloudReady,false);assert.equal(r.steps[1].detail.skills,0);});
test('storage success requires exact readback and deletes only its probe',async()=>{const db=database();db.rows.set('other-user',{value:'keep',sha256:'keep'});const receipt=await probeStorage(db.query,'profile');assert.ok(receipt.verifiedAt);assert.equal(db.rows.size,1);assert.equal(db.rows.get('other-user').value,'keep');});
test('storage corruption fails and removes its probe',async()=>{const db=database(true);await assert.rejects(probeStorage(db.query,'profile'),/readback mismatch/);assert.equal(db.rows.size,0);});
test('reconnection failure clears old success and no credentials are stored',async t=>{const {dir,root}=await fixture(t);const s=await createSetup(join(dir,'profile'),'hermes',[root]);const env={CLOUDFLARE_ACCOUNT_ID:'a'.repeat(32),CLOUDFLARE_D1_DATABASE_ID:'1'.repeat(36),CLOUDFLARE_API_TOKEN:'private-token'};const db=database();await connectSetup(s.profile,{env,queryFactory:()=>db.query});assert.equal((await setupStatus(s.profile)).steps[2].status,'previously-verified');assert.ok(!(await fs.readFile(s.profile,'utf8')).includes('private-token'));await assert.rejects(connectSetup(s.profile,{env:{},queryFactory:()=>{throw Error('expired');}}),/expired/);assert.equal((await setupStatus(s.profile)).steps[2].status,'not-connected');});
test('changed product configuration invalidates the profile',async t=>{const {dir,root}=await fixture(t);const s=await createSetup(join(dir,'profile'),'codex',[root]);const p=JSON.parse(await fs.readFile(s.profile));p.product.defaults.backend='unreviewed';await fs.writeFile(s.profile,JSON.stringify(p));await assert.rejects(setupStatus(s.profile),/changed setup profile/);});
