import {z} from 'zod';
const key=z.string().regex(/^[a-zA-Z0-9][a-zA-Z0-9_-]{0,79}$/);
export const documentSchema=z.object({version:z.literal(1),project:key,skillId:key,kind:z.enum(['run','baseline','proposal','assessment','review']),occurredAt:z.string().datetime({offset:true}).nullable(),mode:z.enum(['summary','evidence']),payload:z.record(z.string(),z.unknown())}).strict();
export const recordSchema=z.object({id:z.string().regex(/^[a-f0-9]{64}$/),document:documentSchema}).strict();
export const querySchema=z.object({project:key,skillId:key,after:z.number().int().nonnegative().max(Number.MAX_SAFE_INTEGER).default(0)});
export function canonical(value:unknown):string {
 if(Array.isArray(value))return '['+value.map(canonical).join(',')+']';
 if(value&&typeof value==='object')return '{'+Object.keys(value).sort().map(k=>JSON.stringify(k)+':'+canonical((value as Record<string,unknown>)[k])).join(',')+'}';
 return JSON.stringify(value);
}
export async function digest(value:unknown){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(canonical(value))))).map(x=>x.toString(16).padStart(2,'0')).join('');}
const summaryKeys=new Set(['id','createdAt','kind','runner','conditions','skillHash','packageHash','passed','total','score','comparison','components','status','decidedAt','runId','baselineId','beforeHash','beforePackageHash','candidatePackageHash','eligible','version','evidenceIdentity','decisions','counts','fullyVerified']);
export async function validateRecord(value:unknown){const record=recordSchema.parse(value);if(record.document.mode==='summary'){for(const key of Object.keys(record.document.payload))if(!summaryKeys.has(key))throw Error('Summary mode cannot contain raw source or output fields');const p=record.document.payload;if(p.comparison)z.object({status:z.string().max(100),delta:z.number().optional(),lostChecks:z.array(z.string().max(160)).optional()}).strict().parse(p.comparison);if(p.components)z.object({counts:z.record(z.string().max(60),z.number()).optional(),fullyVerified:z.boolean().optional()}).strict().parse(p.components);if(p.decisions)z.record(z.string().max(160),z.object({status:z.enum(['accepted','dismissed']),updatedAt:z.string().datetime({offset:true})}).strict()).parse(p.decisions);if(p.counts)z.record(z.string().max(60),z.number()).parse(p.counts);for(const [key,val]of Object.entries(p)){if(['comparison','components','decisions','counts'].includes(key)||val===null)continue;if(!['string','number','boolean'].includes(typeof val)||(typeof val==='string'&&val.length>160))throw Error('Invalid summary value');}}if(new TextEncoder().encode(JSON.stringify(record)).length>700000)throw Error('Archive record exceeds 700 KB; use summary mode');if(await digest(record.document)!==record.id)throw Error('Archive content identity mismatch');return record;}
