import {createAppWorkspace} from 'chumbo/app';
import './style.css';
const root=document.getElementById('workspace'),$=id=>document.getElementById(id);
const workspace=createAppWorkspace({name:'Skill Loop · QA history',version:'0.1.0'},{root});const {app}=workspace;
let query=null,next=null,busy=false;
const text=(tag,content,cls)=>{const el=document.createElement(tag);el.textContent=content;if(cls)el.className=cls;return el;};
const button=(label,fn,cls)=>{const el=text('button',label,cls);el.type='button';el.onclick=fn;return el;};
function message(value){$('notice').textContent=value;}
function payload(result){if(result.isError)throw Error(result.content?.find(c=>c.type==='text')?.text??'The operation failed');if(!result.structuredContent)throw Error('The server returned no structured data');return result.structuredContent;}
async function call(name,args){if(busy)return;busy=true;root.querySelectorAll('button').forEach(b=>b.disabled=true);message('');try{const value=payload(await app.callServerTool({name,arguments:args}));render(value);return value;}catch(e){message(e.message+' Refresh before retrying; no local skill was changed.');}finally{busy=false;root.querySelectorAll('button').forEach(b=>b.disabled=false);}}
function render(data){if(data.record){renderDetail(data);return;}if(!Array.isArray(data.events)||!data.project||!data.skillId)throw Error('Unexpected history response');query={project:data.project,skillId:data.skillId,after:0};next=data.next;$('context').textContent=`${data.project} / ${data.skillId} · archived snapshots · reported scores may use different test conditions`;$('history').replaceChildren();$('more').hidden=next===null;if(!data.events.length)$('history').append(text('p','No history saved for this skill yet.'));for(const row of data.events){const card=text('article','','run'),description=document.createElement('div');description.append(text('small',new Date(row.saved_at).toLocaleString()),text('h2',row.kind),text('p',Number.isFinite(row.summary?.score)?`${row.summary.passed}/${row.summary.total} reported checks`:'Saved evidence snapshot'));card.append(description,button('Inspect QA report',()=>call('get_history_record',{id:row.record_hash})));$('history').append(card);}}
function renderDetail(data){const target=$('detail');target.hidden=false;target.replaceChildren();const d=data.record.document,p=d.payload;target.append(text('h2',`${d.skillId} · ${d.kind}`),text('p',data.qa.status==='rescored-from-supplied-evidence'?`${data.qa.passed}/${data.qa.total} checks recomputed from saved evidence`:`QA status: ${data.qa.status}`),text('p',data.qa.provenance??data.qa.reason??'','dim'));const cases=document.createElement('div');cases.className='cases';for(const c of p.suite?.cases??[]){const row=text('article',''),out=p.response?.outputs?.find(o=>o.id===c.id);row.append(text('h3',c.id),text('small','INPUT'),text('pre',JSON.stringify(c.input,null,2)),text('small','ACTUAL OUTPUT'),text('pre',JSON.stringify(out?.output??null,null,2)));const checks=(data.qa.checks??[]).filter(x=>x.caseId===c.id),more=document.createElement('details');more.append(text('summary','Check evidence'),text('pre',JSON.stringify(checks,null,2)));row.append(more);cases.append(row);}target.append(cases,text('h2','Review findings'),text('p','Accepting a finding requests a fix. These decisions never change automated scores or apply skill revisions.','dim'));if(!data.findings.length)target.append(text('p','No prose findings recorded. This is not a claim of complete quality coverage.'));for(const finding of data.findings){const row=text('article',''),note=document.createElement('textarea');note.maxLength=4000;note.value=finding.note;note.id='note-'+finding.id;const label=text('label','Reason or revision direction');label.htmlFor=note.id;row.append(text('small',finding.status+' · revision '+finding.revision),text('p',finding.finding),label,note);const actions=text('div','','actions');for(const [status,title] of [['accepted','Accept finding'],['dismissed','Dismiss finding'],['pending','Reopen']])actions.append(button(title,()=>{if(status==='dismissed'&&!note.value.trim()){message('Add a reason before dismissing this finding.');note.focus();return;}call('decide_review_finding',{id:finding.id,revision:finding.revision,status,note:note.value.trim()});},status==='accepted'?'primary':''));row.append(actions);target.append(row);}const accepted=data.findings.filter(f=>f.status==='accepted');if(accepted.length){const details=document.createElement('details');details.append(text('summary','Accepted findings for the next revision'),text('pre',accepted.map((f,i)=>`${i+1}. ${f.finding}\n${f.note}`).join('\n\n')));target.append(details);}target.append(button('Download this evidence',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='skill-loop-history-record.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}));}
$('refresh').onclick=()=>query?call('refresh_skill_history',query):message('Ask your assistant to open history for a project and skill.');$('more').onclick=()=>query&&next!==null&&call('refresh_skill_history',{...query,after:next});app.ontoolresult=result=>{try{render(payload(result));}catch(e){message(e.message);}};app.onerror=()=>message('Connection lost. Reopen Skill Loop history to reconnect.');await workspace.connect();
